
name: "terraform-deploy"

on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terrform init

      - name: Terraform Plan
        run: terrafom plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
